import {
  FileText,
  TableProperties,
  Wand2,
  BarChart3,
  History,
  Settings,
} from 'lucide-react';
import { NavigationItem } from '../types/navigation';

export const getNavigationItems = (taskCount: number): NavigationItem[] => [
  {
    id: 'relatorios',
    name: 'Gerador de Relatórios',
    shortName: 'Relatórios',
    description: 'Criação estruturada de apontamentos de atividades e tarefas diárias.',
    category: 'automacoes',
    badge: taskCount > 0 ? `${taskCount}` : 'Ativo',
    badgeVariant: taskCount > 0 ? 'primary' : 'success',
    isReady: true,
    icon: <FileText size={20} />,
  },
  {
    id: 'formatador',
    name: 'Formatador de Dados',
    shortName: 'Formatador',
    description: 'Limpeza, conversão e padronização rápida de textos, CSV e tabelas.',
    category: 'automacoes',
    badge: 'Em breve',
    badgeVariant: 'warning',
    isReady: false,
    icon: <TableProperties size={20} />,
  },
  {
    id: 'modelos',
    name: 'Modelos de Textos Rápidos',
    shortName: 'Modelos',
    description: 'Templates dinâmicos para e-mails, comunicados e respostas automáticas.',
    category: 'automacoes',
    badge: 'Ativo',
    badgeVariant: 'success',
    isReady: true,
    icon: <Wand2 size={20} />,
  },
  {
    id: 'metricas',
    name: 'Métricas & Produtividade',
    shortName: 'Métricas',
    description: 'Análise de tempo consumido por tipo de atividade e indicadores de foco.',
    category: 'automacoes',
    badge: 'Em breve',
    badgeVariant: 'muted',
    isReady: false,
    icon: <BarChart3 size={20} />,
  },
  {
    id: 'historico',
    name: 'Histórico & Arquivos',
    shortName: 'Histórico',
    description: 'Consolidação de atividades anteriores e relatórios salvos localmente.',
    category: 'sistema',
    badge: 'Em breve',
    badgeVariant: 'muted',
    isReady: false,
    icon: <History size={20} />,
  },
  {
    id: 'configuracoes',
    name: 'Configurações do Hub',
    shortName: 'Ajustes',
    description: 'Personalização do ambiente de automações, backup e atalhos rápidos.',
    category: 'sistema',
    badge: 'Em breve',
    badgeVariant: 'muted',
    isReady: false,
    icon: <Settings size={20} />,
  },
];
